version: '3.3'

services:
  php:
    container_name: php_test
    build:
      context: .
      dockerfile: ./php/Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor
  nginx_test:
    container_name: nginx_test
    image: nginx:stable-alpine
    ports:
      - '8081:81'
    volumes:
      - ./public:/var/www/public
      - ./nginx/nginx-default.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php